### ISSUE TITLE
TODO for 1.0 release

### ISSUE THREAD

**Issue by jython234** [BlockServerProject/BlockClient#1]
- [x] Functional Client
  - [x] RakNet packets implemented
  - [x] Implement Batch Packets
  - [x] Implement Split Packets
- [ ] API
